services:
  icr.api:
    build:
      context: .
      dockerfile: ICR.API/Dockerfile
      target: final

    expose:
      - "8080"

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:8080

      # Banco externo separado
      ConnectionStrings__DefaultConnection: Host=gesto-de-membros-icr-db-eb15un;Port=5432;Database=icr_connect;Username=icradmin;Password=ICRDB@2026

      JWT_KEY: ${JWT_KEY:-dev-only-jwt-secret-key-minimum-32-chars!}
      ROOTUSERNAME: ${ROOTUSERNAME:-admin}
      ROOTPASSWORD: ${ROOTPASSWORD:-admin123}

      BASE_DOMAIN: ${BASE_DOMAIN:-icravivalista.com.br}
      Cors__AllowedOrigins__0: https://app.${BASE_DOMAIN:-icravivalista.com.br}

    networks:
      - dokploy-network

    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network

      - traefik.http.routers.icr-api-web.rule=Host(`api.icravivalista.com.br`)
      - traefik.http.routers.icr-api-web.entrypoints=web
      - traefik.http.routers.icr-api-web.middlewares=redirect-to-https@file
      - traefik.http.routers.icr-api-web.service=icr-api-web
      - traefik.http.services.icr-api-web.loadbalancer.server.port=8080

      - traefik.http.routers.icr-api-websecure.rule=Host(`api.icravivalista.com.br`)
      - traefik.http.routers.icr-api-websecure.entrypoints=websecure
      - traefik.http.routers.icr-api-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.icr-api-websecure.service=icr-api-websecure
      - traefik.http.services.icr-api-websecure.loadbalancer.server.port=8080

  icr.fe:
    image: ghcr.io/davifigueiracarvalho/icr-gestao-secretaria-fe:latest
    pull_policy: always

    expose:
      - "3000"

    environment:
      ICR_API_URL: ${ICR_API_URL:-https://api.icravivalista.com.br}
      VITE_API_URL: ${VITE_API_URL:-https://api.icravivalista.com.br}

    depends_on:
      - icr.api

    networks:
      - dokploy-network

    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network

      - traefik.http.routers.icr-fe-web.rule=Host(`app.icravivalista.com.br`)
      - traefik.http.routers.icr-fe-web.entrypoints=web
      - traefik.http.routers.icr-fe-web.middlewares=redirect-to-https@file
      - traefik.http.routers.icr-fe-web.service=icr-fe-web
      - traefik.http.services.icr-fe-web.loadbalancer.server.port=3000

      - traefik.http.routers.icr-fe-websecure.rule=Host(`app.icravivalista.com.br`)
      - traefik.http.routers.icr-fe-websecure.entrypoints=websecure
      - traefik.http.routers.icr-fe-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.icr-fe-websecure.service=icr-fe-websecure
      - traefik.http.services.icr-fe-websecure.loadbalancer.server.port=3000

networks:
  dokploy-network:
    external: true
