version: "3.9"

services:
  icr_db:
    image: postgres:16
    container_name: icr_db
    environment:
      POSTGRES_DB: icr_connect
      POSTGRES_USER: icradmin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - icr-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icradmin -d icr_connect"]
      interval: 5s
      timeout: 5s
      retries: 5

  icr.api:
    container_name: icr_api
    build:
      context: .
      dockerfile: ICR.API/Dockerfile
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app/ICR.API
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=icr_db;Port=5432;Database=icr_connect;Username=icradmin;Password=root
      JWT_KEY: KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
    depends_on:
      icr_db:
        condition: service_healthy
    networks:
      - icr-net

networks:
  icr-net:
    driver: bridge
