// <auto-generated />
using System;
using ICR.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICR.Infrastructure.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20260325180814_ninguemliga")]
    partial class ninguemliga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICR.Domain.Model.CellAggregate.Cell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChurchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ResponsibleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("cells");
                });

            modelBuilder.Entity("ICR.Domain.Model.ChurchAggregate.Church", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FederationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinisterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FederationId");

                    b.HasIndex("MinisterId");

                    b.ToTable("church");
                });

            modelBuilder.Entity("ICR.Domain.Model.FamilyAggregate.Family", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CellId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChurchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ManId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("WeddingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("WomanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ManId");

                    b.HasIndex("WomanId");

                    b.ToTable("families");
                });

            modelBuilder.Entity("ICR.Domain.Model.FederationAggregate.Federation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("MinisterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MinisterId");

                    b.ToTable("federation");
                });

            modelBuilder.Entity("ICR.Domain.Model.MemberAggregate.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CellPhone")
                        .HasColumnType("text");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<long>("FamilyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBeenMarried")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("ICR.Domain.Model.MinisterAggregate.Minister", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CardValidity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MinisterOrdinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PresbiterOrdinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("minister");
                });

            modelBuilder.Entity("ICR.Domain.Model.RepassAggregate.Reference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CompetenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("reference");
                });

            modelBuilder.Entity("ICR.Domain.Model.RepassAggregate.Repass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<long>("ChurchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("repass");
                });

            modelBuilder.Entity("ICR.Domain.Model.UserRoleAgreggate.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MinimalScope")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ICR.Domain.Model.UserRoleAgreggate.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("ICR.Domain.Model.UserRoleAgreggate.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role");
                });

            modelBuilder.Entity("ICR.Domain.Model.CellAggregate.Cell", b =>
                {
                    b.HasOne("ICR.Domain.Model.ChurchAggregate.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICR.Domain.Model.MemberAggregate.Member", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Church");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("ICR.Domain.Model.ChurchAggregate.Church", b =>
                {
                    b.HasOne("ICR.Domain.Model.FederationAggregate.Federation", "Federation")
                        .WithMany()
                        .HasForeignKey("FederationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICR.Domain.Model.MinisterAggregate.Minister", "Minister")
                        .WithMany()
                        .HasForeignKey("MinisterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("ICR.Domain.Model.Address", "Address", b1 =>
                        {
                            b1.Property<long>("ChurchId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ZipCode");

                            b1.HasKey("ChurchId");

                            b1.ToTable("church");

                            b1.WithOwner()
                                .HasForeignKey("ChurchId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Federation");

                    b.Navigation("Minister");
                });

            modelBuilder.Entity("ICR.Domain.Model.FamilyAggregate.Family", b =>
                {
                    b.HasOne("ICR.Domain.Model.CellAggregate.Cell", "Cell")
                        .WithMany()
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICR.Domain.Model.ChurchAggregate.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICR.Domain.Model.MemberAggregate.Member", "Man")
                        .WithMany()
                        .HasForeignKey("ManId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ICR.Domain.Model.MemberAggregate.Member", "Woman")
                        .WithMany()
                        .HasForeignKey("WomanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cell");

                    b.Navigation("Church");

                    b.Navigation("Man");

                    b.Navigation("Woman");
                });

            modelBuilder.Entity("ICR.Domain.Model.FederationAggregate.Federation", b =>
                {
                    b.HasOne("ICR.Domain.Model.MinisterAggregate.Minister", "Minister")
                        .WithMany()
                        .HasForeignKey("MinisterId");

                    b.Navigation("Minister");
                });

            modelBuilder.Entity("ICR.Domain.Model.MemberAggregate.Member", b =>
                {
                    b.HasOne("ICR.Domain.Model.FamilyAggregate.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("ICR.Domain.Model.MinisterAggregate.Minister", b =>
                {
                    b.HasOne("ICR.Domain.Model.MemberAggregate.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ICR.Domain.Model.Address", "Address", b1 =>
                        {
                            b1.Property<long>("MinisterId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ZipCode");

                            b1.HasKey("MinisterId");

                            b1.ToTable("minister");

                            b1.WithOwner()
                                .HasForeignKey("MinisterId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ICR.Domain.Model.RepassAggregate.Repass", b =>
                {
                    b.HasOne("ICR.Domain.Model.ChurchAggregate.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICR.Domain.Model.RepassAggregate.Reference", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("ICR.Domain.Model.UserRoleAgreggate.User", b =>
                {
                    b.HasOne("ICR.Domain.Model.MemberAggregate.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ICR.Domain.Model.UserRoleAgreggate.UserRole", b =>
                {
                    b.HasOne("ICR.Domain.Model.UserRoleAgreggate.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICR.Domain.Model.UserRoleAgreggate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
